<a href="https://colab.research.google.com/github/nidhiss29/aiml/blob/main/regdemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#problem - predict the salary on basis of years of experience
#how much salary after one year
#person 1 yr experience than what will be salary

In [ ]:
#import necessary libraries
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
#read data
data = pd.read_csv('/content/Salary.csv')

In [ ]:
#check last record tail tells last 5 records
data.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
#yrs of experience independent feature and salary is target


In [ ]:
#split data for X and Y
x = data.drop('Salary', axis=1).values
y=data['Salary'].values

In [ ]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [ ]:
from sklearn.linear_model import LinearRegression
#simply search for algorithms code on internet

In [ ]:
model = LinearRegression()
#fitting the model : mapping input with output
#predict the values
model.fit(x,y)
y_pred = model.predict(x) #test model
y_pred

array([ 36187.15875227,  38077.15121656,  39967.14368085,  44692.12484158,
        46582.11730587,  53197.09093089,  54142.08716303,  56032.07962732,
        56032.07962732,  60757.06078805,  62647.05325234,  63592.04948449,
        63592.04948449,  64537.04571663,  68317.03064522,  72097.0155738 ,
        73987.00803809,  75877.00050238,  81546.97789525,  82491.9741274 ,
        90051.94398456,  92886.932681  , 100446.90253816, 103281.8912346 ,
       108006.87239533, 110841.86109176, 115566.84225249, 116511.83848464,
       123126.81210966, 125016.80457395])

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_pred,y,squared=False))



5592.043608760661


In [ ]:
#single linear regression as 1 column feature
#if multiple columns then multiple linear regression

In [ ]:
print(model_coef)